image: coqorg/coq:8.12.2

build-job:
  stage: build
  script:
    - cd libraries/
    # coq_path.sh の内容の変更は、 Docker Image を使うことにより、既に coq の実行ファイルがパスに含まれているので、不要である。
    - ./build.sh

test-job:
  stage: test
  script:
    - echo "The test has not been implemented yet."

deploy-gitlab-pages:
  stage: deploy
  script:
    - echo "This job has not been implemented yet."
