name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 1 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: coqorg/coq:8.13.2
    steps:
      - uses: actions/checkout@v2
      - run: cd libraries/ && ./compile.sh
